services:
  postgres:
    container_name: postgres
    build: ./srcs
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./subject:/subject
    networks:
      - creationofdb
    env_file:
      - .env
    restart: always

networks:
  creationofdb:
    driver: bridge